package com.example.studentprofileapp

import android.os.Bundle
import android.view.View
import android.widget.EditText
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.widget.doAfterTextChanged
import com.google.android.material.textfield.TextInputLayout

class MainActivity : AppCompatActivity() {

    // UI references
    private lateinit var tilName: TextInputLayout
    private lateinit var tilStudentId: TextInputLayout
    private lateinit var tilCourse: TextInputLayout
    private lateinit var tilYear: TextInputLayout
    private lateinit var tilHometown: TextInputLayout

    private lateinit var etName: EditText
    private lateinit var etStudentId: EditText
    private lateinit var etCourse: EditText
    private lateinit var etYear: EditText
    private lateinit var etHometown: EditText

    private lateinit var tvResult: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_main)

        // Keep content clear of the status bar, nav bar, and keyboard
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val bars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            val ime = insets.getInsets(WindowInsetsCompat.Type.ime())
            v.setPadding(bars.left, bars.top, bars.right, maxOf(bars.bottom, ime.bottom))
            insets
        }

        bindViews()

        // Typing in a field clears that field's inline error
        wireAutoClearError(tilName, etName)
        wireAutoClearError(tilStudentId, etStudentId)
        wireAutoClearError(tilCourse, etCourse)
        wireAutoClearError(tilYear, etYear)
        wireAutoClearError(tilHometown, etHometown)

        findViewById<View>(R.id.btnGenerate).setOnClickListener { generateProfile() }
        findViewById<View>(R.id.btnClear).setOnClickListener { clearForm() }
    }

    private fun bindViews() {
        tilName = findViewById(R.id.tilName)
        tilStudentId = findViewById(R.id.tilStudentId)
        tilCourse = findViewById(R.id.tilCourse)
        tilYear = findViewById(R.id.tilYear)
        tilHometown = findViewById(R.id.tilHometown)

        etName = findViewById(R.id.etName)
        etStudentId = findViewById(R.id.etStudentId)
        etCourse = findViewById(R.id.etCourse)
        etYear = findViewById(R.id.etYear)
        etHometown = findViewById(R.id.etHometown)

        tvResult = findViewById(R.id.tvResult)
    }

    /**
     * Reads every field, validates, and either shows the profile
     * generated by the Java ProfileGenerator class or a validation message.
     */
    private fun generateProfile() {
        clearFieldErrors()

        val fields = listOf(
            tilName to etName,
            tilStudentId to etStudentId,
            tilCourse to etCourse,
            tilYear to etYear,
            tilHometown to etHometown
        )
        val values = fields.associate { it.second to it.second.text.toString().trim() }
        val emptyFields = fields.filter { values[it.second].isNullOrEmpty() }

        if (emptyFields.isNotEmpty()) {
            // Highlight each missing field and show a validation message
            emptyFields.forEach { it.first.error = getString(R.string.error_required) }
            emptyFields.first().second.requestFocus()

            tvResult.setTextColor(ContextCompat.getColor(this, R.color.colorError))
            tvResult.text = getString(R.string.validation_message)
            return
        }

        // All fields complete -> let the Java class build the profile
        val generator = ProfileGenerator()
        val profile = generator.generateProfile(
            values.getValue(etName),
            values.getValue(etStudentId),
            values.getValue(etCourse),
            values.getValue(etYear),
            values.getValue(etHometown)
        )

        tvResult.setTextColor(ContextCompat.getColor(this, R.color.textDefault))
        tvResult.text = profile
    }

    /** Clears all inputs and resets the result to its default message. */
    private fun clearForm() {
        clearFieldErrors()
        etName.text.clear()
        etStudentId.text.clear()
        etCourse.text.clear()
        etYear.text.clear()
        etHometown.text.clear()

        tvResult.setTextColor(ContextCompat.getColor(this, R.color.textPlaceholder))
        tvResult.setText(R.string.result_placeholder)
    }

    private fun clearFieldErrors() {
        listOf(tilName, tilStudentId, tilCourse, tilYear, tilHometown)
            .forEach { it.error = null }
    }

    private fun wireAutoClearError(til: TextInputLayout, et: EditText) {
        et.doAfterTextChanged { til.error = null }
    }
}
